:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  # Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  # https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
  # proyecto lo cree con --skip-active-storage el video le wagon asi lo hace, entonces eso de arriba dos lineas no deberian ir pero lo estoy dejando
